# Generated by Django 3.1 on 2021-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=70)),
                ('Address_1', models.CharField(max_length=255)),
                ('Address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(max_length=100)),
                ('Post_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('News_letter', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
